config/routes.rb
Rails.application.routes.draw do
  resources :goobs

  devise_for :users
  root "goobs#index"
  get "about" => "pages#about"  # creates about_path

end

app/models/goob.rb
class Goob < ActiveRecord::Base
	belongs_to :user
	
	has_attached_file :image, :styles => { :large => "450x450", :medium => "300x300>", :thumb => "100x100>" },
							  :storage => :s3,
							  :bucket => 'Shmeebler'
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :goobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:last_name, :first_name) }

    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:last_name, :first_name)}

  end

end

app/controllers/goobs_controller.rb
class GoobsController < ApplicationController
  before_action :set_goob, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @goobs = Goob.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  def show
  end

  def new
    @goob = current_user.goobs.build
  end

  def edit
  end

  def create
    @goob = current_user.goobs.build(goob_params)

      if @goob.save
        redirect_to @goob, notice: 'Goob was successfully created.'
      else
        render action: 'new'
      end
  end

  def update
      if @goob.update(goob_params)
        redirect_to @goob, notice: 'Goob was successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
    @goob.destroy
    redirect_to goobs_url
  end

  private

    def set_goob
      @goob = Goob.find(params[:id])
    end

    def correct_user
      @goob = current_user.goobs.find_by(params[:id])
      redirect_to goobs_path, notice: "Get Chya Weight Up Son!!!" if @goob.nil?
    end

    def goob_params
      params.require(:goob).permit(:description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	
  end

  def about
  	
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goobs_helper.rb
module GoobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/goobs/_form.html.erb
<%= form_for @goob, html: { multipart: true } do |f| %>
  <% if @goob.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goob.errors.count, "error") %> prohibited this goob from being saved:</h2>

      <ul>
      <% @goob.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/goobs/edit.html.erb
<h1>Editing goob</h1>

<%= render 'form' %>

<%= link_to 'Show', @goob %> |
<%= link_to 'Back', goobs_path %>

app/views/goobs/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="goobs" class="transitions-enabled">
  <% @goobs.each do |goob| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(goob.image.url(:medium)), goob %>
      <div class="panel-body">
        <%= goob.description %><br/>
        <strong><%= goob.user.email if goob.user %></strong>
        <% if goob.user == current_user %>
          <div class="actions">
            <%= link_to 'Edit', edit_goob_path(goob) %>
            <%= link_to 'Delete', goob_path(goob), method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @goobs, renderer: BootstrapPagination::Rails %>
</div>

app/views/goobs/new.html.erb
<h1>New goob</h1>

<%= render 'form' %>

<%= link_to 'Back', goobs_path %>

app/views/goobs/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @goob.image.url(:large) %>
      </div>
      <div class="panel-body">
        <p><%= @goob.description %></p>
        <p><strong><%= @goob.user.email if @goob.user %></strong></p>

        <% if @goob.user == current_user %>
         <%= link_to 'Edit', edit_goob_path(@goob) %>
        <% end %>
        | <%= link_to 'Back', goobs_path %>

      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ol class="nav navbar-nav">
        <li><%= link_to "Shmeebler", root_path, class:'navbar-brand' %></li>
      </ol>
      
      <ol class="nav navbar-nav navbar-right">
        <li>  <%= link_to 'New Goob', new_goob_path %></li>
        <li><%= link_to "Goobs", goobs_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      	<% else %>
		  <li><%= link_to "Log in", new_user_session_path %></li>
		<% end %>      
      </ol>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>Shmeebler</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Previous line is a view helper that prevents cross-site request forgeries when users input data in forms-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">  
  <!--Previous line makes it so mobile devices don't look funny-->

</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<link href='http://fonts.googleapis.com/css?family=Asap|Muli|Fjalla+One|Play|Audiowide|Playfair+Display+SC|Satisfy' rel='stylesheet' type='text/css'>

<div class="jumbotron center">
		<h1 font-family='Muli'>Welcome to Shmeebler</h1>
		<p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
<h1>About</h1>
<p>My name is John, and this is my web application - Shmeebler. I created this application while 
   in the One Month Rails course Pinteresting. At the time of this writing I have no idea what   
   I want to do with it. I just want it to be useful to me to start off with and then have it grow from there. 
</p>
<p>   
   My user name on Github is J0hnnyC33
</p>
</div>

app/views/pages/home.html.erb
<link href='http://fonts.googleapis.com/css?family=Asap|Muli|Fjalla+One|Play|Audiowide|Playfair+Display+SC|Satisfy' rel='stylesheet' type='text/css'>

<div class="jumbotron center">
	<% if user_signed_in? %>
		You're signed in.
	<% else %>
		<h1 font-family='Muli'>Welcome to Shmeebler</h1>
		<p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
	<% end %>
</div>